[avito]
tg_token = ""
tg_chat_id = [
    "",
]
urls = [
    "https://www.avito.ru/all/gruzoviki_i_spetstehnika/buldozery-ASgBAgICAURU3E0?cd=1",
    "https://www.avito.ru/krasnodar/telefony/mobilnye_telefony/apple/iphone_16-ASgBAgICA0SywA3GsYwVtMANzqs5sMENiPw3?cd=1",
]
count = 3
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 9999999999
min_price = 1000
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 20
pause_between_links = 2
max_age = 0
max_count_of_retry = 5
ignore_reserv = false
ignore_promotion = false
one_time_start = false
one_file_for_link = false
save_xlsx = true

save_json = false
