[avito]
tg_token = ""
tg_chat_id = []
vk_token = ""
vk_user_id = []
urls = [
    "https://www.avito.ru/all/telefony/mobilnye_telefony/apple/iphone_11-ASgBAgICA0SywA2kmzm0wA3OqzmwwQ2I_Dc?cd=1&f=ASgBAQECA0SywA2kmzm0wA3OqzmwwQ2I_DcBQOjrDkT~_dsC_P3bAvr92wL4_dsCAUXGmgwUeyJmcm9tIjowLCJ0byI6OTAwMH0&s=104&user=1",
]
count = 1
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 9000
min_price = 1000
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 20
pause_between_links = 2
max_age = 0
max_count_of_retry = 5
ignore_reserv = false
ignore_promotion = false
one_time_start = false
one_file_for_link = false
parse_views = false
save_xlsx = false
use_webdriver = true
