services:
  parser_avito:
    container_name: avito
    image: ghcr.io/duff89/parser_avito:latest
      #build:
      #  context: .
      #  dockerfile: Dockerfile
        #tags:
        #  - localhost/parser_avito:latest
    restart: always
    volumes:
       - $PWD/config.toml:/app/config.toml:ro
       - $PWD/cookies.json:/app/cookies.json:Z
       - $PWD/result:/app/result:Z
       - $PWD/database.db:/app/database.db:Z
       #- $PWD/state.json:/app/state.json:Z
